services:
  vio-odometry:
    build:
      context: ./docker
      dockerfile: vio.dockerfile
      target: dev-ws

    image: vio_dev
    container_name: vio

    command: tail -f /dev/null
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - ./vio_workspace:/home/vio_dev/vio_workspace